import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globalIcons.css";
import { ReduxProvider } from "./redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`font-xl bg-PomoInActive font-semibold ${inter.className} no-scrollbar overflow-y-scroll`}
			>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
